### ISSUE TITLE
Bakeware temp directory not found

### ISSUE THREAD

**Issue by janpieper** [eigr/spawn#121]
**Describe the bug**

I wanted to have a look into spawn and deployed the manifest to my kubernetes cluster, but the pod fails to start:

```console
$ kubectl logs -f -n eigr spawn-operator-679b5dfbc9-bbz9f
bakeware: Error creating directory /app/.cache/bakeware/.tmp/gGaFkn??: No such file or directory
bakeware: Unrecoverable validation error
```

```console
$ kubectl describe pod -n eigr-functions spawn-operator-679b5dfbc9-bbz9f
[...]

Containers:
  spawn-operator:
    Container ID:   containerd://2071d4906138cde79a728a55e393ea1e852fb27261d7cf8145d80e5d8eaa0f73
    Image:          eigr/spawn-operator:0.5.0-rc.7
    Image ID:       docker.io/eigr/spawn-operator@sha256:4788f13dc1112bc6bf07d8dc156b833e67652dc7211c7d56b9d91ec168ed9741
    Port:           <none>
    Host Port:      <none>
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 16 Jan 2023 19:07:20 +0100
      Finished:     Mon, 16 Jan 2023 19:07:20 +0100
    Ready:          False
    Restart Count:  8
    Limits:
      cpu:     200m
      memory:  200Mi
    Requests:
      cpu:     200m
      memory:  200Mi
    Environment:
      MIX_ENV:                    prod
      BONNY_POD_NAME:             spawn-operator-679b5dfbc9-bbz9f (v1:metadata.name)
      BONNY_POD_NAMESPACE:        eigr-functions (v1:metadata.namespace)
      BONNY_POD_IP:                (v1:status.podIP)
      BONNY_POD_SERVICE_ACCOUNT:   (v1:spec.serviceAccountName)
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-wslrx (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kube-api-access-wslrx:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Guaranteed
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                   From               Message
  ----     ------     ----                  ----               -------
  Normal   Scheduled  17m                   default-scheduler  Successfully assigned eigr-functions/spawn-operator-679b5dfbc9-bbz9f to nuccy
  Normal   Pulling    17m                   kubelet            Pulling image "eigr/spawn-operator:0.5.0-rc.7"
  Normal   Pulled     17m                   kubelet            Successfully pulled image "eigr/spawn-operator:0.5.0-rc.7" in 4.894598973s
  Normal   Created    16m (x5 over 17m)     kubelet            Created container spawn-operator
  Normal   Started    16m (x5 over 17m)     kubelet            Started container spawn-operator
  Normal   Pulled     16m (x4 over 17m)     kubelet            Container image "eigr/spawn-operator:0.5.0-rc.7" already present on machine
  Warning  BackOff    2m40s (x72 over 17m)  kubelet            Back-off restarting failed container
```

**To Reproduce**

Just run the default installation steps:

```bash
kubectl create ns eigr-functions && \
  curl -L https://github.com/eigr/spawn/releases/download/v0.5.0-rc.7/manifest.yaml | kubectl apply -f -
```

Wait a few seconds and check the logs of the spawn-operator pod.

**Expected behavior**

Pod starts without a problem.

**Additional context**

Kubernetes: v1.25.2
Spawn: v0.5.0-rc.7

**Comment by sleipnir** [comment]
Hello @janpieper first thank you very much for testing Spawn.
I'll take a look at it. This was an old bug, we may have reintroduced this bug in recent versions.

**Comment by sleipnir** [comment]
Hi @janpieper Palliatively you can run the following deployment on your cluster in the **eigr-functions** namespace. This will allow you to upload the Operator's container and POD in your cluster until we make the final fix.

PS: I also updated the container image to the latest release.

Deployment:

```yaml
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    k8s-app: spawn-operator
  name: spawn-operator
  namespace: eigr-functions
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: spawn-operator
  template:
    metadata:
      labels:
        k8s-app: spawn-operator
    spec:
      containers:
        - env:
            - name: MIX_ENV
              value: prod
            - name: BONNY_POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: BONNY_POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: BONNY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: BONNY_POD_SERVICE_ACCOUNT
              valueFrom:
                fieldRef:
                  fieldPath: spec.serviceAccountName
          image: eigr/spawn-operator:0.5.0-rc.8
          name: spawn-operator
          resources:
            limits:
              cpu: 200m
              memory: 200Mi
            requests:
              cpu: 200m
              memory: 200Mi
          volumeMounts:
            - mountPath: /app/.cache/bakeware/
              name: bakeware-cache
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65534
      volumes:
        - name: bakeware-cache
          emptyDir: {}
      serviceAccountName: spawn-operator
```
